on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Change directory to swapp
        run: cd swapp
      - name: Install dependencies
        working-directory: swapp
        run: npm ci
      - name: Build
        working-directory: swapp
        run: npm run build --if-present
      - name: Test
        working-directory: swapp
        run: npm test
